### ISSUE TITLE
Notifications for lock/unlock events

### ISSUE THREAD

**Issue by kind3r** [kind3r/hass-addons#1]
Placeholder issue to avoid duplicates from people asking for this feature.
This is actually an upstream issue and depends on the SDK to activate those notifications.

If you want to help, please check https://github.com/kind3r/ttlock-sdk-js/issues/5

**Comment by nonkronk** [comment]
Is the mqtt features only able to check the lock/unlock status?
I can't find the way to lock/unlock the device with lovelace ui or mqtt publish

**Comment by kind3r** [comment]
Hi @nonkronk , sorry for the late reply.
The addon exposes a [Lock](https://www.home-assistant.io/integrations/lock/) device which can be added to lovelace and used ini automations just like any other lock. You can find the device and view more details under Configuration -> Integrations -> MQTT -> click on the number of devices and find it in the list.
![image](https://user-images.githubusercontent.com/1621814/112710208-0b5a4200-8ec8-11eb-8aae-7813c0553d06.png)

For those following this thread, there is now a new version available that implements reading the operation log and update HA about lock/unlock events. Due to how this works expect a delay between the unlock event and the update in HA, this is the same way the official gateway detects this events and it's a limitation of the lock protocol itself.
