### ISSUE TITLE
Problem during building addon

### ISSUE THREAD

**Issue by shuenpin** [kind3r/hass-addons#10]
Hello 

I can not install this addon, because failed on build.

The detail log is

21-04-28 18:51:47 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for 8dc774ce/armv7-addon-ttlock-hass-integration:0.4.0
21-04-28 18:51:54 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build 8dc774ce/armv7-addon-ttlock-hass-integration:0.4.0: The command '/bin/ash -o pipefail -c apk update' returned a non-zero code: 2
21-04-28 18:51:54 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/19 : ARG BUILD_FROM

Step 2/19 : FROM $BUILD_FROM

 ---> 4217c0d7148d

Step 3/19 : ENV LANG C.UTF-8

 ---> Using cache

 ---> 88662ca0cd2b

Step 4/19 : RUN apk update

 ---> Running in b95642071aaf

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz

ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz

ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory

2 errors; 43 distinct packages available

Removing intermediate container b95642071aaf

Please help me to solve, Thank you.

**Comment by kind3r** [comment]
Looks like some issue accessing the alpine repositories. You should retry.

**Comment by shuenpin** [comment]
@kind3r I solve this issue via upgrade libseccomp2 packages

Please follow blow link for detail
https://github.com/alpinelinux/docker-alpine/issues/135#issuecomment-816603722

Thank you.
