### ISSUE TITLE
Can't get this configured

### ISSUE THREAD

**Issue by ackerthehacker2** [kind3r/hass-addons#18]
I know I am missing something in the configuration ....  this is my log ....

> ttlock-hass-integration@0.2.1 start /app
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Server started

**Comment by Fusseldieb** [comment]
Hi,
from another issue kind3r commented:

> The missing lockData.json file indeed is nothing to worry about as it will be generated after the first lock is paired. But the `/data` folder needs to exist.

Have you created the /data folder?

After creating it, you should be able to try and pair your lock, that is, if it's been reset first.

**Comment by kind3r** [comment]
There is no need to create the /data folder, this is done by HA automatically. Those errors are normal on first runs until some lock is paired and the files are populated. I will remove them at some point.
