### ISSUE TITLE
For Passcode only Permanent option is enabled

### ISSUE THREAD

**Issue by dibyadip-das** [kind3r/hass-addons#20]
Please refer to the below screenshot for more details:
![Screenshot 2021-07-12 at 1 10 10 AM](https://user-images.githubusercontent.com/47345141/125208089-1c2f9780-e2ae-11eb-82d3-b2138e59c31d.png)

All other options are disabled. Is this an issue with my 🔒 or it is a known bug ?

**Comment by Fusseldieb** [comment]
It's still planned to be integrated, see: https://github.com/kind3r/ttlock-sdk-js

```
## Planned development
- [ ] cyclic based validity setup for credentials (ex.: Mo-Fr from 9AM to 5PM)
```

This isn't a bug

**Comment by dibyadip-das** [comment]
Thanks for the quick reply. Looking forward to the update. Amazing work guys 👍 Keep up the good work 🥇
