### ISSUE TITLE
No user interface after clean install

### ISSUE THREAD

**Issue by lexvx** [kind3r/hass-addons#27]
I installed the add-on, but when I go to the UI, I get this:

https://sun9-63.userapi.com/impg/wjnRd83rUXw7--PDxRysn104f0gkVXQ8PLTThg/6l-UxkPfXwM.jpg?size=986x925&quality=96&sign=227d3d3f5db54482195893fe31105129&type=album]

And it always enpty...

Here is log:
`> ttlock-hass-integration@0.2.1 start
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Monitor started
Server started
Discovered unknown lock: {"id":"e62f125b5ca6","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"E6:2F:12:5B:5C:A6","rssi":-68,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":true,"isSettingMode":false,"txPowerLevel":0,"batteryCapacity":65,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}`

**Comment by kind3r** [comment]
Hi @lexvx ,

Your lock is not in pairing mode `"isSettingMode":false`

You can't pair a lock that is already paired to the official TTLock app, you need to unpair or reset it.
