### ISSUE TITLE
I'm Buying one, and want to help :)

### ISSUE THREAD

**Issue by vitinhosessa** [kind3r/hass-addons#3]
Man, i really liked this project.

~I'm about to buy one, and i created this issue because i found on aliexpress the lock with the gateway with the same price or lower.~

Probably i'm gonna buy this one, and maybe i can help you.

What are the chances that we will achieve nothing with the gateway?

~Here is the link for the lock + gateway: https://www.aliexpress.com/item/4000730028210.html?spm=a2g0s.8937460.0.0.f95b2e0eTdxabT~

PS: Sorry if i did something wrong 😬

**Comment by kind3r** [comment]
@vitinhosessa DON'T !!!
That's the one I got (or very similar) and it's WiFi Tuya version. It will not work with BLE and the WiFi is only ON when you phisically interact with the lock. So basically the lock is always offline, unless you touch the keyboard.

**Comment by vitinhosessa** [comment]
Thanks for the advice.

Why do they do this? They dont even say tuya on the page.

Do you have a link with the one that works, and even the one with the gateway? because I'm still interested :)

Sorry for my rusty english, i'm from Brazil.

**Comment by kind3r** [comment]
It does say "WIFI App Electronic Door Lock" in the description, but TTLock on the pictures, I'm really confused. Maybe you should ask the seller to make sure. Maybe @Fusseldieb can help as he has 3 :D

**Comment by Fusseldieb** [comment]
I bought exactly these: https://pt.aliexpress.com/item/4000054070174.html?spm=a2g0s.9042311.0.0.2742b90aG4BdYd

@vitinhosessa

**Comment by kind3r** [comment]
I just got my lock from @Fusseldieb 's link and it works. Still waiting for the gateway :)
