### ISSUE TITLE
Config settings for G2 Gateway

### ISSUE THREAD

**Issue by J4YRD** [kind3r/hass-addons#30]
Hey, hoping I can get this working, because it will be awesome. Is there any way to find the config settings for the G2 Gateway? I saw you mentioned it in the notes but I can find out how to add my gateway. Thanks.

**Comment by kind3r** [comment]
Hi, the G2 gateway only works with the TTLock app and cloud services. The purpose of this project is to have an offline integration that does not rely on the TTLock cloud.
