### ISSUE TITLE
How about the bluetooth gateway?

### ISSUE THREAD

**Issue by felipecrs** [kind3r/hass-addons#32]
Hi, first, amazing project.

I started looking for smart locks to buy and integrate with my HA, and then I found your project and https://github.com/kind3r/hass-addons/issues/3. The model suggested there is very cool, but my door would not be close to my HA server, so direct connection via Bluetooth would not work for me.

I see that there is a gateway: https://aliexpress.com/item/33014871696.html

Any advice on this? Would it work with this project? I guess no, as it says that it requires Bluetooth.

Thank you!

**Comment by kind3r** [comment]
Hi @felipecrs ,

That is the official TTLock gateway that works with their app via their cloud. The goal of this project was to build an direct/offline integration that does not depend on their cloud.

 There is another project that uses an ESP32-WROVER module as a bluetooth gateway: https://github.com/kind3r/esp32-ble-gateway exactly for the purpose of extending the bluetooth range.

In theory, their official gateway could be repurposed to work as a BLE extender, but someone would have to write a firmware for that. Also, it's way more expensive than an ESP32 module.

**Comment by kind3r** [comment]
> > the limitation is only one BLE gateway, for now.
> 
> Is this a limitation of the addon? Or the locks?

Of the addon. When I built it, living in an apartment building, I did not think that people will use more than one lock (like for entry). But again, it is possible to adapt and use multiple gateways + embeded BLE. The catch would be deciding which one should connect to which lock and how to report RSSI.
