### ISSUE TITLE
Error: ENOENT - I find the smart lock but I can't connect

### ISSUE THREAD

**Issue by andycarlos1hassio** [kind3r/hass-addons#33]
Hi

I find the smart lock but I can't connect

I did the clean installation in a new home assistant, from what I understand in the logs my lock is being found, however the shortcut to configure (in the left menu) does not respond.

![image](https://user-images.githubusercontent.com/91729563/137263209-6114fb81-3a1e-4de7-b57d-e49413c0d7e4.png)

LOG:
`> ttlock-hass-integration@0.2.1 start
> node ./index.js
[Error: ENOENT: no such file or directory, access '/data/lockData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/lockData.json'
}
[Error: ENOENT: no such file or directory, access '/data/aliasData.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/data/aliasData.json'
}
MQTT connected
Monitor started
**Discovered unknown lock: {"id":"e255f3a57f52","manufacturer":"unknown","model":"unknown","hardware":"unknown","firmware":"unknown","address":"E2:55:F3:A5:7F:52","rssi":-97,"protocolType":5,"protocolVersion":3,"scene":2,"groupId":0,"orgId":0,"lockType":5,"isTouch":true,"isUnlock":false,"hasEvents":false,"isSettingMode":false,"txPowerLevel":0,"batteryCapacity":59,"date":0,"isWristband":false,"isRoomLock":true,"isSafeLock":false,"isBicycleLock":false,"isLockcar":false,"isGlassLock":false,"isPadLock":false,"isCyLinder":false,"isRemoteControlDevice":false,"isDfuMode":false,"isNoLockService":false,"remoteUnlockSwitch":0,"disconnectStatus":0,"parkStatus":0,"lockSound":-1,"autoLockTime":-1,"privateData":{},"operationLog":[]}
Server started`**

**Comment by kind3r** [comment]
Hi, 2 issues here:
1. Your lock is not in pairing mode `"isSettingMode":false`
2. Signal strength is very low `"rssi":-97` you should have the lock closer for better stability

You can't pair a lock that is already paired to the official TTLock app, you need to unpair or reset it.
